#!/usr/bin/env bash
# Server-01 login commands

# Setting up the SSH-agent
eval $("ssh-agent")

# Path to IdentityFile
ssh-add ~/.ssh/school

# Username and IP Address 
# old username and IP Address (ssh ubuntu@52.205.86.40)
ssh ubuntu@54.82.132.136
