#!/usr/bin/env bash
# Server-01 login commands

# Setting up the SSH-agent
eval $("ssh-agent")

# Path to IdentityFile
ssh-add ~/.ssh/school

# Username and IP Address 
# old username and IP Address for web2 (ssh ubuntu@100.26.170.43)
ssh ubuntu@52.201.168.15
